export enum LeaveTypeEnum {
  SICK_LEAVE = 'SICK_LEAVE',
  YEAR_LEAVE = 'YEAR_LEAVE',
  MATERNITY_LEAVE = 'MATERNITY_LEAVE',
  MARRIAGE_LEAVE = 'MARRIAGE_LEAVE',
  PATERNITY_LEAVE = 'PATERNITY_LEAVE',
}
