export enum LeaveTypeEnum {
  SICK_LEAVE = 'SICK_LEAVE',
  ANNUAL_LEAVE = 'ANNUAL_LEAVE',
  MATERNITY_LEAVE = 'MATERNITY_LEAVE',
  MARRIAGE_LEAVE = 'MARRIAGE_LEAVE',
  PATERNITY_LEAVE = 'PATERNITY_LEAVE',
}
